/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Gth */

#ifndef _Included_org_Gth
#define _Included_org_Gth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Gth
 * Method:    grassmanTH
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Gth_grassmanTH
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
